apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres  
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        resources:
          requests:
            memory: 128Mi
            cpu: 750m
          limits:
            memory: 512Mi
            cpu: "1"
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_DB 
      #   volumeMounts:
      #   - name: postgres-database-storage
      #     mountPath: /var/lib/pgsql/data
      # volumes:
      # - name: postgres-database-storage
      #   persistentVolumeClaim:
      #     claimName: postgres-pv-claim